language: node_js
node_js:
- '8'
install:
- npm install
script:
- npm test
- npm run build
after_success:
- npm run coveralls
branches:
  only:
  - master
deploy:
  provider: npm
  email: yarnbCoder@gmail.com
  skip_cleanup: true
  api_key:
    secure: krA+nmvfGvSaiwDBqb4KCtYALYlffkB854O6owsuWh/y3RSyB03EQ+OQ9Ml4An319TBdjVTaHPuiUnHcuN7cj+bhNF3S6WLXV7BR4mYPQypZeb509/YgdiN0oLC7UYJKmU0EHkIGzgX0zeeKVx894/1Jo9JEezW1VnR2SbuePKTaI1AskOLA6RnzmLPuju5YPrTlAhSX4fo3axJ7hsgok0EBfBM33esipdReazLwz9xBXbj9l+gC3o/LTlCViJqVvXohR+xnqSWfIANxw1BmgvroB9suhqBoWN3q3jAx4sSxgka31Q69R7WhBLW/DMiWelHpw658DyR95468gBqwjZNe0AQezI7Atsep6YHzAOXv2U0dZHLafS4TuCWrFVGX/NvkB3mNdiTdKI5KHXYkvrbHroZpzEGzBETslK3PIcRAzgUa2FajZQG0v+4lmOOMT67eAkXZ+AxXY2A31o5+JvPxg+KML7xfn89B49F0oPW6EHU4qVG8Lj7G7h6oGgmjJ6vn2rfHdA21eSYXrAVW3iOGL0XCJ2NjCQO/WF3t0MfmGJSEIMkfP5rD8FPk5g8TZtBhi53C6sMlkwl3XyvM9QjmN+505fRj+QPvGWTyuItD8PuxZbx2vicp7mj195PWBrvnHzVChCsTmadzjOv8t6Dw5DG5Swn1Um42zW6+yW0=
  on:
    tags: true
    repo: tolerance-go/wepyx
    branch: master
